datasource:
  mysql:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:33660/leave_system?useUnicode=true&characterEncoding=UTF-8
    username: rex
    password: ji394su3
  mariadb:
    driver-class-name: org.mariadb.jdbc.Driver
    jdbcUrl: jdbc:mariadb://localhost:32768/test_db
    username: root
    password: ji394su3