# Atomikos datasource
datasource:
  mysql:
    xa-data-source-class-name: com.mysql.cj.jdbc.MysqlXADataSource
    xa-properties:
      url: jdbc:mysql://192.168.43.201:33660/leave_system?useUnicode=true&characterEncoding=UTF-8
      user: rex
      password: 1
#  mariadb:
#    xa-data-source-class-name: org.mariadb.jdbc.MySQLDataSource
#    xa-properties:
#      url: jdbc:mariadb://localhost:32768/test_db
#      user: root
#      password: ji394su3
# normal datasource
#datasource:
#  mysql:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    jdbcUrl: jdbc:mysql://localhost:33660/leave_system?useUnicode=true&characterEncoding=UTF-8
#    username: rex
#    password: ji394su3
#  mariadb:
#    driver-class-name: org.mariadb.jdbc.Driver
#    jdbcUrl: jdbc:mariadb://localhost:32768/test_db
#    username: root
#    password: ji394su3